# Auto-generated from Formula/hung-detect.rb.tmpl by `make package`. Do not edit this file directly.
class HungDetect < Formula
  desc "Detect Not Responding macOS GUI apps via Activity Monitor private signal"
  homepage "https://github.com/fjh658/hung_detect"
  license "Apache-2.0"
  version "0.5.1"

  tap_root = Pathname.new(__dir__).parent
  artifact = tap_root/"dist"/"hung-detect-0.5.1-macos-universal.tar.gz"
  url "file://#{artifact}"
  sha256 "afe2ae8acdccd87fe730ee51d97f734b5088a6c815c9e98eca107c968f744c79"

  depends_on :macos

  def install
    bin.install "hung_detect"
  end

  test do
    assert_match "hung_detect", shell_output("#{bin}/hung_detect --help")
  end
end
