# Auto-generated from Formula/hung-detect.rb.tmpl by `make package`. Do not edit this file directly.
class HungDetect < Formula
  desc "Detect Not Responding macOS GUI apps via Activity Monitor private signal"
  homepage "https://github.com/fjh658/hung_detect"
  license "Apache-2.0"
  version "0.5.0"

  tap_root = Pathname.new(__dir__).parent
  artifact = tap_root/"dist"/"hung-detect-0.5.0-macos-universal.tar.gz"
  url "file://#{artifact}"
  sha256 "d7de9d80ef99a33c267a1ede5a5f76c512492328f200f6a8f03167c41779ae9b"

  depends_on :macos

  def install
    bin.install "hung_detect"
  end

  test do
    assert_match "hung_detect", shell_output("#{bin}/hung_detect --help")
  end
end
